package org.jbundle.util.biorhythm;

import java.awt.*;

/**
 * This class was generated by a SmartGuide using IBM's Visual Age for Java.
 * Then, I changed the method names, so they are more descriptive.
 */
public class BioBean extends Biorhythm
	implements java.beans.PropertyChangeListener, Constants
{
	/**
     * 
     */
    private static final long serialVersionUID = 1L;
    
    /**
	 * Creates new Model.
	 */
	public BioBean()
	{
		super();
		this.init();
	}
	/**
	 * Creates new Control.
	 */
	public void init()
	{
		View view = new LegendView(null);
		Model model = new Model(view);
		m_controller = new LegendController(model, null, null, null);
		view.setController(m_controller);
//		this.getContentPane().add(BorderLayout.NORTH, m_controller);	// Dont add!
		this.getContentPane().add(BorderLayout.CENTER, view);
		this.getContentPane().setBackground(view.getElementColor(BACKGROUND));
	}
	/**
	 * Set the birth date.
	 * @param strDate The new birthdate in standard system-parsable format.
	 */
	public void setBirthdate(String strDate)
	{
		super.setBirthdate(strDate);
	}
	/**
	 * Set the start date.
	 * @param strDate The new start date in standard system-parsable format.
	 */
	public void setStartDate(String strDate)
	{
		super.setStartDate(strDate);
	}
	/**
	 * Set the start date.
	 * @param strDate The new end date in standard system-parsable format.
	 */
	public void setEndDate(String strDate)
	{
		super.setEndDate(strDate);
	}
	/**
	 * Get the birthdate.
	 * @return The birthdate in standard system format.
	 */
	public String getBirthdate()
	{
		return super.getBirthdate();
	}
	/**
	 * Get the start date.
	 * @return The start date in standard system format.
	 */
	public String getStartDate()
	{
		return super.getStartDate();
	}
	/**
	 * Get the end date.
	 * @return The end date in standard system format.
	 */
	public String getEndDate()
	{
		return super.getEndDate();
	}
}
